# .streamlit/secrets.toml
[connections.snowflake]
account = "xxxxxxx-xxxxxxx"
user = "APMW4DABW"
password = "4ppsRUs49"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = TRUE
